apiVersion: batch/v1
kind: CronJob
metadata:
  name: summarize-rss
  namespace: summarize-rss
spec:
  schedule: "0 6 * * *" # 毎日6時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: summarize-rss
            image: ghcr.io/a-takamin/summarize-rss:main
            envFrom:
            - secretRef:
                name: summarize-rss-secret
          restartPolicy: OnFailure
