apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: summarize-rss
  namespace: argocd
  labels:
    app: summarize-rss
spec:
  project: default

  source:
    repoURL: https://github.com/a-takamin/ouchi-k8s.git
    targetRevision: main
    path: apps/summarize-rss/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: summarize-rss

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
