apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-pv
  labels:
    app: freshrss
    type: freshrss-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # データを保持（削除時も残る）
  storageClassName: local-storage
  hostPath: # hostPath はノードのファイルシステムを直接使うので、1台構成だから許されている
    path: /var/lib/k8s-volumes/freshrss
    type: DirectoryOrCreate  # ディレクトリが存在しなければ自動作成
